### ISSUE TITLE
How to play without moving axes 

### ISSUE THREAD

**Issue by isabellearcher** [mprozil/PlayAxis#1]
Hello,

When I press play, the data points on my scatter & area chart stay stable & instead the axes scales move forward. How do I change the settings to keep the scales stable & move the data points instead?

Thank you.

**Comment by mprozil** [comment]
Hi, 
This visual works like a slicer so unfortunately, unless the chart allows "Highlight" instead of "Filter", which is not the case for scatter or area charts, you will get that behavior. 
I don't know if its an option for your reports but you could disable the interaction between those specific charts and the PlayAxis or replace them with charts that allow highlight such as barcharts. You can see interaction options if you select the visual and then go to the Visual Tools - Format - Edit Interactions.
Hope it helps somehow.
