### ISSUE TITLE
Issue with Custom ToolTips

### ISSUE THREAD

**Issue by kgmccann** [mprozil/PlayAxis#5]
When using this visualization, custom tooltips on the same page of the report fail to load at first. They flicker in and out and the user then has to reposition the mouse slightly to get them to load again.

It does not seem to affect auto-tooltips, and it does not matter whether interactions between the slicer and elements are active or not.  Also, this does not seem to be a problem with other custom visualizations I have used.

**Comment by mprozil** [comment]
I'm sorry but I'm not able to reproduce the issue. Do you have a small example that you can send so I can understand the problem better?

**Comment by iuriemaxim** [comment]
We had a different, but still similar behavior with tooltips in our own developed custom visual, but this is not because of the slicer, but because of the tooltip in custom visual that is controlled by the slicer.
For example when a tooltip is over a country in a custom map visual showing the value for that particular country and the Axis slicer is in play mode, the value in the tooltip is not changing.
Probably the developer of the custom visual mentioned by kgmccann, tried to implement something in order for the tooltip to change the values, but it flicker instead.
There is nothing you can do, but this is for you and others to understand the issue with tooltips on some custom visuals when animation is enabled.
