### ISSUE TITLE
When hitting stop the slicer select all values instead the first one

### ISSUE THREAD

**Issue by iuriemaxim** [mprozil/PlayAxis#7]
Indeed, most slicers are by default selecting no value, which actually means all values are selected.
But for such a play, pause and stop slicer it is important to have a different behavior.
Supposing that the slicer is playing years from 2005 to 2010. If autoplay is not enabled, than, by default the slicer will show all data for 2005-2010 years. However, a user is expecting to see the 2005 year instead, if the data is ordered ascending or 2010 year if the data is ordered descending.
In order this to happen, the user should hit play and then hit pause. This is actually how the slicer should be initialized.
When hitting stop, the slicer should go to the first year (2005 or 2010, depending on the sorting order).

The chiclet slicer solved this with an option "Forced selection". If this is set to on, then a single value is selected and is not possible to have "none" selected that actually means that all values are selected.

To better understand, when using the Play Axis slicer in combination with a map visual and the user wants to see the evolution in time, than first thing he see is the data for all years.  This is confusing as the map is incorrect, making a sum of all values or showing first values that are actualy not corresponding to the first year, but to the first record.

The solution to enable autoplay by default is not an option.

Hope it can be fixed easily.

There are three great slicers for Power BI:  this one, the chiclet slicer and the hierarchy slicer, and only the first two allows to see map evolution in time, the first without human intervention but with the issue mentioned, second with human selecting year by year.

Well done,
Iurie

**Comment by iuriemaxim** [comment]
Solved.

**Comment by raiken77** [comment]
Thanks a lot for this widget! @iuriemaxim, I am experiencing the same issue as what you described. I'm using an integer value representing the year as the data field for the play axis widget. Since the widget has no default value, it is showing a sum of all the values across the years at the beginning until I start pressing play where it filters correctly.

I tried the version from the powerBI app store and also the one from master branch dist folder but none of them uses a default value for the year. How did you solve this?
